// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';

show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJub5JYZWbV2ot4zkvHEUjSw7igigdpDo',
    appId: '1:643939785174:web:149a7f317fb09ea64e6c77',
    messagingSenderId: '643939785174',
    projectId: 'miwau---android',
    authDomain: 'miwau---android.firebaseapp.com',
    storageBucket: 'miwau---android.firebasestorage.app',
    measurementId: 'G-HET65S9G09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAth_NPU_F8ht7klleP1g_098ln1oBpvYA',
    appId: '1:643939785174:android:8c1ccb52394029024e6c77',
    messagingSenderId: '643939785174',
    projectId: 'miwau---android',
    storageBucket: 'miwau---android.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJub5JYZWbV2ot4zkvHEUjSw7igigdpDo',
    appId: '1:643939785174:web:149a7f317fb09ea64e6c77',
    messagingSenderId: '643939785174',
    projectId: 'miwau---android',
    authDomain: 'miwau---android.firebaseapp.com',
    storageBucket: 'miwau---android.firebasestorage.app',
    measurementId: 'G-HET65S9G09',
  );
}
